local nerdy = require('nerdy')

describe('nerdy', function()
    it('has the right functions defined', function()
        assert.is_function(nerdy.list)
        assert.is_function(nerdy.get)
    end)

    describe('get function', function()
        it('returns the correct character for a valid icon name', function()
            local char = nerdy.get('cod-account')
            assert(char == '', 'Expected cod-account icon character to be ""')
        end)

        it('returns the correct character for another valid icon name', function()
            local char = nerdy.get('cod-add')
            assert(char == '', 'Expected cod-add icon character to be ""')
        end)

        it('returns empty string for non-existent icon', function()
            local char = nerdy.get('non-existent-icon')
            assert(char == '', 'Expected empty string for non-existent icon')
        end)

        it('returns empty string for nil input', function()
            local char = nerdy.get(nil)
            assert(char == '', 'Expected empty string for nil input')
        end)

        it('returns empty string for empty string input', function()
            local char = nerdy.get('')
            assert(char == '', 'Expected empty string for empty string input')
        end)
    end)
end)
