import requests

min = 62721
max = 65535

lua_str = '-- Do not edit this file. Run python scripts/generatory.py.\
\nlocal function get_icons()\n  local icons = {\n'

indent = '    '

target = open('./lua/nerdy/icons.lua', 'w')
target.write(lua_str)

url = 'https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/glyphnames.json'
response = requests.get(url)
data = response.json()

for i in data:
    if i != 'METADATA':
        code = int(str(data[i]['code']), 16)
        if code < min or code > max:
            char = str(data[i]['char'])
            target.write(indent + '["' + i + '"] = "' + char + '",\n')

target.write('  }\n return icons\nend\nreturn {\n  get_icons = get_icons,\n}')
target.close()
