import requests

lua_str = '-- Do not edit this file directly. Run python scripts/generator.py.\nreturn {\n'

indent = '    '

target = open('./lua/nerdy/icons.lua', 'w')
target.write(lua_str)

url = 'https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/glyphnames.json'
response = requests.get(url)
data = response.json()

for i in data:
    if i != 'METADATA':
        code = int(str(data[i]['code']), 16)
        char = str(data[i]['char'])
        target.write(indent + '["' + i + '"] = "' + char + '",\n')

target.write('}')
target.close()
